### PR TITLE
Basic speakers/talks pages

### PR DESCRIPTION
**Pull request by gandalfar**
WIP for talks/speakers pages

- [x] Check that all Bios are in 3rd person.
- [x] Remove all links to promo material from speakers' bios

### CODE REVIEW

**Comment by gandalfar** [comment]
@inesp I've added speaker images and improved templates for speakers. Please review if I missed something obvious and then we can release the page.

@zanderle also exported all the talks and they're in the repo.

**Comment by inesp** [comment]
I did the first 8 talks, don't merge yet, I still have to do the rest :)

(Also: really bad average text quality :disappointed:  .)

**Comment by inesp** [comment]
@zanderle can you please ask Chelsea Dole to give a short (2-5) sentences description of her talk?

**Comment by inesp** [comment]
@zanderle Will Emily Karungi have her talk alone or with somebody? She keeps using "we"

**Comment by zanderle** [comment]
@inesp I will when I get online. Emily will give her talk with another speaker. I’ll get you the details. Also, I think we should check with speakers if they’re ok with these changes (the ones that aren’t simple typos and formatting fixes) before publishing cc @gandalfar

**Comment by inesp** [comment]
> Emily will give her talk with another speaker.

Do we have the name of the other person? We need to add it to the description, and we need a bio for them.

**Comment by inesp** [comment]
> Also, I think we should check with speakers if they’re ok with these changes (the ones that aren’t simple typos and formatting fixes) before publishing cc @gandalfar

Yes, definitely. Ideally, we would completely replace my changes with their new text once we tell me the format. Lots of these texts were written for the conference organizers, not for the website.

**Pull request merged**
